# SAVE ME AS config.yml!

token: BOTTOKEN
avatar: avatar.png
mute_role: Susturulmu≈ü
img_dir: images/
img_url_prefix: https://example.com/discord-img/
admin_roles:
  - Admin
cleverbot_channels: # (#)'a gerek yok.
  - bot
speak_person: # This person will make the bot speak if he PMs it.
  name: admicos
  iden: 5389 # The number after "#" in his username.